name: Arduino CI
on: [push, pull_request]
jobs:
  compile-sketch:
    strategy:
      matrix:
        arduino-platform: ["esp32:m5stack_stickc_plus", "esp32:m5stack_stickc_plus2", "esp32:m5stack_atom", "esp32:m5stack_atoms3"]
        #arduino-platform: ["esp32:m5stack_stickc_plus", "esp32:m5stack_stickc_plus2"]
        include:
          - arduino-platform: "esp32:m5stack_stickc_plus"
            fqbn: "m5stack:esp32:m5stack_stickc_plus"
          - arduino-platform: "esp32:m5stack_stickc_plus2"
            fqbn: "m5stack:esp32:m5stack_stickc_plus2"
          - arduino-platform: "esp32:m5stack_atom"
            fqbn: "m5stack:esp32:m5stack_atom"
          - arduino-platform: "esp32:m5stack_atoms3"
            fqbn: "m5stack:esp32:m5stack_atoms3"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2
      - name: Install platform and librafies
        run: |
          arduino-cli config set network.connection_timeout 600s
          arduino-cli config add board_manager.additional_urls https://static-cdn.m5stack.com/resource/arduino/package_m5stack_index.json
          arduino-cli core update-index
          arduino-cli core install m5stack:esp32
          arduino-cli lib update-index
          arduino-cli lib install FastLED
          arduino-cli lib install WiFi
          arduino-cli lib install M5Unified
          arduino-cli lib install M5UnitASR
      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }}
